### PR TITLE
add spring feature and fix vtk index issue

### LINKED ISSUE #535: Define time span to generate vtk
Instead of defining the total number of vtks generated we can define the time span that is linked with the animation FPS required.

### PR DESCRIPTION
**Pull request by jorgepz**
closes #535  and solves first sub-task of issue #535

### CODE REVIEW

File: src/core/assembler.m [hunk 1]
```diff
@@ -342,6 +342,7 @@
   indsIK = indsIK(1:counterInds) ;
   indsJK = indsJK(1:counterInds) ;
   valsK  = valsK (1:counterInds) ;
+%  norm(KS)
```
Comment (jorgepz) [inline src/core/assembler.m:345]:
```suggestion
```

**Review by mvanzulli — APPROVED** [review]
Excelenchi!
